output: docs
author: gematik Gesellschaft für Telematikanwendungen der Gesundheitskarte mbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: ASN1Kit
github_url: https://build.top.local/source/git/refImpl/mobszen/iOS/ASN1Kit
theme: jony
xcodebuild_arguments:
  - "-project"
  - 'ASN1Kit.xcodeproj'
  - "-scheme"
  - 'ASN1Kit-Package'
