name: ASN1Kit
options:
  bundleIdPrefix: de.gematik.ti.common
  deploymentTarget:
    macOS: 10.12
    iOS: 12.1
settings:
  base:
    VERSIONING_SYSTEM: "apple-generic"
    CURRENT_PROJECT_VERSION: -1
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  ASN1Kit:
    type: framework
    platform: [macOS, iOS]
    info:
      path: Resources/ASN1Kit_Info.plist
    sources:
      - Sources/ASN1Kit
    dependencies:
      - carthage: GemCommonsKit
      - carthage: DataKit
    scheme:
      testTargets:
        - ASN1KitTests_${platform}
      gatherCoverageData: true
  SwiftLibsShadow:
    type: framework
    platform: macOS
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: ASN1Kit_macOS
        embed: true
      - carthage: Commandant
        embed: true
      - carthage: DataKit
        embed: true
      - carthage: GemCommonsKit
        embed: true
      - carthage: ObjCCommonsKit
        embed: true
    scheme:
  asn1c:
    type: tool
    platform: macOS
    settings:
        base:
            SWIFT_FORCE_DYNAMIC_LINK_STDLIB: YES
            SWIFT_FORCE_STATIC_LINK_STDLIB: NO
            LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/SwiftLibsShadow.framework/Versions/Current/Frameworks"
    sources:
      - Sources/CLI
    dependencies:
      - target: SwiftLibsShadow
      - target: ASN1Kit_macOS
      - carthage: Commandant
      - carthage: DataKit
      - carthage: GemCommonsKit
      - carthage: ObjCCommonsKit
  ASN1KitTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/ASN1Kit_Tests_Info.plist
    sources:
      - path: Tests/ASN1KitTests
    dependencies:
      - target: ASN1Kit_${platform}
      - carthage: Nimble
buildImplicitDependencies: true
